/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistenciasistema;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danny
 */
public class Interfaz1 extends javax.swing.JFrame {
    
    public Clase claseManana = new Clase("Trigonometria"); 
    
    public Clase claseTarde = new Clase("Geometria");
    public Clase claseNoche = new Clase("Algebra");
    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        claseManana.getAlumnos()[0]=new Alumno("Marco");
        claseManana.getAlumnos()[1]=new Alumno("Francisco");
        claseManana.getAlumnos()[2]=new Alumno("Jose");
        claseManana.getAlumnos()[3]=new Alumno("Rodrigo");
        claseManana.getAlumnos()[4]=new Alumno("Juan");
        claseManana.getAlumnos()[5]=new Alumno("Jorge");
        claseManana.getAlumnos()[6]=new Alumno("Beto");
        claseManana.getAlumnos()[7]=new Alumno("Anibal");
        claseManana.getAlumnos()[8]=new Alumno("Marcelo");
        claseManana.getAlumnos()[9]=new Alumno("Mateo");
        
        claseTarde.getAlumnos()[0]=new Alumno("Marco1");
        claseTarde.getAlumnos()[1]=new Alumno("Francisco1");
        claseTarde.getAlumnos()[2]=new Alumno("Jose1");
        claseTarde.getAlumnos()[3]=new Alumno("Rodrigo1");
        claseTarde.getAlumnos()[4]=new Alumno("Juan1");
        claseTarde.getAlumnos()[5]=new Alumno("Jorge1");
        claseTarde.getAlumnos()[6]=new Alumno("Beto1");
        claseTarde.getAlumnos()[7]=new Alumno("Anibal1");
        claseTarde.getAlumnos()[8]=new Alumno("Marcelo1");
        claseTarde.getAlumnos()[9]=new Alumno("Mateo1");
        
        claseNoche.getAlumnos()[0]=new Alumno("Marco11");
        claseNoche.getAlumnos()[1]=new Alumno("Francisco11");
        claseNoche.getAlumnos()[2]=new Alumno("Jose11");
        claseNoche.getAlumnos()[3]=new Alumno("Rodrigo11");
        claseNoche.getAlumnos()[4]=new Alumno("Juan11");
        claseNoche.getAlumnos()[5]=new Alumno("Jorge11");
        claseNoche.getAlumnos()[6]=new Alumno("Beto11");
        claseNoche.getAlumnos()[7]=new Alumno("Anibal11");
        claseNoche.getAlumnos()[8]=new Alumno("Marcelo11");
        claseNoche.getAlumnos()[9]=new Alumno("Mateo11");
        initComponents();
        String turno=  (String) jComboBox1.getSelectedItem();
        System.out.print(turno);
         Clase clase = claseManana;
        if("Manana".equals(turno)){
            clase = claseManana;
        }
        if("Tarde".equals(turno)){
            clase = claseTarde;
        }
        if("Noche".equals(turno)){
            clase = claseNoche;
        }
        jRadioButton1.setText(clase.getAlumnos()[0].getNombre());
        jRadioButton2.setText(clase.getAlumnos()[1].getNombre());
        jRadioButton3.setText(clase.getAlumnos()[2].getNombre());
        jRadioButton4.setText(clase.getAlumnos()[3].getNombre());
        jRadioButton5.setText(clase.getAlumnos()[4].getNombre());
        jRadioButton6.setText(clase.getAlumnos()[5].getNombre());
        jRadioButton7.setText(clase.getAlumnos()[6].getNombre());
        jRadioButton8.setText(clase.getAlumnos()[7].getNombre());
        jRadioButton9.setText(clase.getAlumnos()[8].getNombre());
        jRadioButton10.setText(clase.getAlumnos()[9].getNombre());
        visualizar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("A1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("A1");

        jRadioButton3.setText("A1");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("A1");

        jRadioButton5.setText("A1");

        jRadioButton6.setText("A1");

        jRadioButton7.setText("A1");

        jRadioButton8.setText("A1");

        jRadioButton9.setText("A1");

        jRadioButton10.setText("A1");

        jButton1.setText("Ingresar Asistencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Silla", "Nombre", "Fecha", "Curso", "Asistio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manana", "Tarde", "Noche" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String turno=  (String) jComboBox1.getSelectedItem();
        System.out.print(turno);
         Clase clase = claseManana;
        if("Manana".equals(turno)){
            clase = claseManana;
        }
        if("Tarde".equals(turno)){
            clase = claseTarde;
        }
        if("Noche".equals(turno)){
            clase = claseNoche;
        }
        jRadioButton1.setText(clase.getAlumnos()[0].getNombre());
        jRadioButton2.setText(clase.getAlumnos()[1].getNombre());
        jRadioButton3.setText(clase.getAlumnos()[2].getNombre());
        jRadioButton4.setText(clase.getAlumnos()[3].getNombre());
        jRadioButton5.setText(clase.getAlumnos()[4].getNombre());
        jRadioButton6.setText(clase.getAlumnos()[5].getNombre());
        jRadioButton7.setText(clase.getAlumnos()[6].getNombre());
        jRadioButton8.setText(clase.getAlumnos()[7].getNombre());
        jRadioButton9.setText(clase.getAlumnos()[8].getNombre());
        jRadioButton10.setText(clase.getAlumnos()[9].getNombre());
        visualizar();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fecha = fechaActual.format(formatter);
        Clase clase = claseManana;
        String turno=  (String) jComboBox1.getSelectedItem();
        System.out.print(turno);
        if("Manana".equals(turno)){
            clase = claseManana;
        }
        if("Tarde".equals(turno)){
            clase = claseTarde;
        }
        if("Noche".equals(turno)){
            clase = claseNoche;
        }
        String curso = clase.getCurso();
        clase.ingresarAsistencia(0,jRadioButton1.isSelected(),fecha);
        clase.ingresarAsistencia(1,jRadioButton2.isSelected(),fecha);
        clase.ingresarAsistencia(2,jRadioButton3.isSelected(),fecha);
        clase.ingresarAsistencia(3,jRadioButton4.isSelected(),fecha);
        clase.ingresarAsistencia(4,jRadioButton5.isSelected(),fecha);
        clase.ingresarAsistencia(5,jRadioButton6.isSelected(),fecha);
        clase.ingresarAsistencia(6,jRadioButton7.isSelected(),fecha);
        clase.ingresarAsistencia(7,jRadioButton8.isSelected(),fecha);
        clase.ingresarAsistencia(8,jRadioButton9.isSelected(),fecha);
        clase.ingresarAsistencia(9,jRadioButton10.isSelected(),fecha);
        visualizar();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void visualizar(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Clase clase = claseManana;
        String turno=  (String) jComboBox1.getSelectedItem();
        System.out.print(turno);
        if("Manana".equals(turno)){
            clase = claseManana;
        }
        if("Tarde".equals(turno)){
            clase = claseTarde;
        }
        if("Noche".equals(turno)){
            clase = claseNoche;
        }
        System.out.println(clase.actual);
        for(int i = 0 ; i< clase.actual;i++){
             for(int j = 0 ; j< 10;j++){
                boolean asistio = clase.getAlumnos()[j].getAsistencias()[i].asistio;
                String fecha=clase.getAlumnos()[j].getAsistencias()[i].fecha;
                String nombre = clase.getAlumnos()[j].getNombre();
                String curso = clase.curso;
                Object[] row = {j, nombre, fecha,curso,asistio};
                model.addRow(row);
             }  
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
